
package com.bank.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServerInterface", targetNamespace = "http://ws.bank.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServerInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkCcValidity", targetNamespace = "http://ws.bank.com/", className = "com.bank.client.CheckCcValidity")
    @ResponseWrapper(localName = "checkCcValidityResponse", targetNamespace = "http://ws.bank.com/", className = "com.bank.client.CheckCcValidityResponse")
    @Action(input = "http://ws.bank.com/WebServerInterface/checkCcValidityRequest", output = "http://ws.bank.com/WebServerInterface/checkCcValidityResponse")
    public int checkCcValidity(
        @WebParam(name = "arg0", targetNamespace = "")
        CreditCard arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processPayment", targetNamespace = "http://ws.bank.com/", className = "com.bank.client.ProcessPayment")
    @ResponseWrapper(localName = "processPaymentResponse", targetNamespace = "http://ws.bank.com/", className = "com.bank.client.ProcessPaymentResponse")
    @Action(input = "http://ws.bank.com/WebServerInterface/processPaymentRequest", output = "http://ws.bank.com/WebServerInterface/processPaymentResponse")
    public int processPayment(
        @WebParam(name = "arg0", targetNamespace = "")
        CreditCard arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
